export const en = {
    common: {
        dashboard: "Dashboard",
        newMeeting: "New Meeting",
        processingQueue: "Processing Queue",
        reviewEdit: "Review & Edit",
        exportMinutes: "Export Minutes",
        settings: "Settings",
        signOut: "Sign Out",
        save: "Save",
        cancel: "Cancel",
        loading: "Loading...",
        success: "Success",
        error: "Error",
        thai: "Thai",
        english: "English",
        bilingual: "Bilingual"
    },
    dashboard: {
        welcome: "Welcome to BBIK MOM Generator",
        subtitle: "Professional AI-powered meeting minutes assistant.",
        recentTasks: "Recent Tasks",
        noTasks: "No recent tasks found.",
        startNew: "Start New Meeting"
    },
    settings: {
        title: "System Configuration",
        subtitle: "Fine-tune the AI generation and document output parameters.",
        aiSection: "Artificial Intelligence",
        modelLabel: "Intelligence Model",
        modelHelper: "Better models give more accurate insight but may take longer to process.",
        outputSection: "Document Output",
        langLabel: "Primary Language",
        langHelper: "Controls the language used for generated summaries and action items.",
        pmoLabel: "Signatory / Saved By",
        pmoHelper: "This name will appear at the bottom of generated DOCX files.",
        saveBtn: "Save Configuration",
        saveSuccess: "Settings saved successfully"
    },
    record: {
        title: "Live Audio Recorder",
        recording: "Recording...",
        paused: "Paused",
        stop: "Stop",
        start: "Start",
        pause: "Pause",
        resume: "Resume",
        saveTitle: "Save Recording",
        namePlaceholder: "Meeting Name",
        processBtn: "Process & Generate Minutes",
        downloadMp3: "Download MP3"
    },
    landing: {
        welcomePrefix: "Welcome back",
        recentMeetings: "Recent Meetings",
        recentSubtitle: "History of your processed meeting intelligence",
        viewAll: "View All",
        activeTasks: "Active Tasks",
        activeSubtitle: "Real-time AI processing",
        noActive: "No active tasks running at the moment.",
        processedCount: "MEETINGS PROCESSED",
        activeCount: "ACTIVE TASKS",
        managerBtn: "Open Tasks Manager",
        readAnalysis: "Read Analysis",
        tableTitle: "Meeting Title",
        tableDateTime: "Date & Time",
        tableStatus: "Status",
        tableID: "ID"
    },
    processing: {
        initializing: "Initializing...",
        step: "Step",
        complete: "Processing Complete!",
        failed: "Error occurred",
        cancelled: "Task Cancelled",
        logsTitle: "Real-time Pipeline Logs",
        downloadBtn: "Download DOCX",
        cancelBtn: "Cancel Process",
        closeBtn: "Close",
        statusComplete: "COMPLETE",
        statusFailed: "FAILED",
        statusCancelled: "CANCELLED"
    },
    queue: {
        title: "Processing Queue",
        subtitle: "Real-time status of AI meeting generation and historical logs.",
        clearHistory: "Clear History",
        pipelineStatus: "Pipeline Status",
        activeQueue: "Active Queue",
        running: "Running",
        noActive: "No active tasks running. Start a new meeting to begin.",
        logsTitle: "Processing Logs",
        statusFeed: "Status Feed",
        taskHistory: "Task History",
        noHistory: "No history found.",
        cancelConfirm: "Are you sure you want to cancel this task?",
        deleteConfirm: "Remove this task from history?",
        clearConfirm: "Clear all completed/failed tasks from history?",
        downloadFailed: "Download failed. Result might have been cleared.",
        cancelBtn: "Cancel Task"
    },
    setup: {
        title: "Prepare Your Meeting",
        subtitle: "Provide the context required for the AI to generate accurate minutes and action items.",
        metadataTitle: "Meeting Metadata",
        metadataDesc: "Essential Identifying Information for the meeting minutes record.",
        fieldTitle: "Meeting Title",
        fieldBU: "Department / Business Unit",
        fieldTemplate: "Minutes Template",
        fieldDate: "Date",
        fieldTime: "Start Time",
        fieldAgenda: "Agenda",
        participantsTitle: "Participants",
        participantsDesc: "Tag all attendees. This improves speaker identification accuracy during transcription.",
        participantPlaceholder: "Add email address or name...",
        addBtn: "Add",
        proceedBtn: "Proceed to Recording",
        errorEmpty: "Please fill in required fields (Title, Date, Start Time)",
        stepSetup: "SETUP",
        stepRecord: "RECORD",
        stepProcess: "PROCESS",
        stepReview: "REVIEW",
        stepExport: "EXPORT"
    }
};
