export const th = {
    common: {
        dashboard: "แดชบอร์ด",
        newMeeting: "การประชุมใหม่",
        processingQueue: "คิวการประมวลผล",
        reviewEdit: "ตรวจสอบและแก้ไข",
        exportMinutes: "ส่งออกรายงาน",
        settings: "ตั้งค่า",
        signOut: "ออกจากระบบ",
        save: "บันทึก",
        cancel: "ยกเลิก",
        loading: "กำลังโหลด...",
        success: "สำเร็จ",
        error: "ข้อผิดพลาด",
        thai: "ภาษาไทย",
        english: "ภาษาอังกฤษ",
        bilingual: "สองภาษา"
    },
    dashboard: {
        welcome: "ยินดีต้อนรับสู่ BBIK MOM Generator",
        subtitle: "ผู้ช่วยสร้างรายงานการประชุมอัจฉริยะด้วย AI",
        recentTasks: "งานล่าสุด",
        noTasks: "ไม่พบงานล่าสุด",
        startNew: "เริ่มการประชุมใหม่"
    },
    settings: {
        title: "การตั้งค่าระบบ",
        subtitle: "ปรับแต่งพารามิเตอร์การสร้าง AI และการส่งออกเอกสาร",
        aiSection: "ปัญญาประดิษฐ์ (AI)",
        modelLabel: "โมเดลประมวลผล",
        modelHelper: "โมเดลที่ฉลาดกว่าจะให้ข้อมูลที่แม่นยำกว่า แต่อาจใช้เวลาประมวลผลนานกว่า",
        outputSection: "การส่งออกเอกสาร",
        langLabel: "ภาษาหลักที่ใช้",
        langHelper: "ควบคุมภาษาที่ใช้ในการสรุปและรายการสิ่งที่ต้องทำ",
        pmoLabel: "ผู้ลงนาม / ผู้บันทึก",
        pmoHelper: "ชื่อนี้จะปรากฏที่ด้านล่างของไฟล์ DOCX ที่สร้างขึ้น",
        saveBtn: "บันทึกการตั้งค่า",
        saveSuccess: "บันทึกการตั้งค่าสำเร็จ"
    },
    record: {
        title: "เครื่องบันทึกเสียง",
        recording: "กำลังบันทึก...",
        paused: "หยุดชั่วคราว",
        stop: "หยุด",
        start: "เริ่ม",
        pause: "พัก",
        resume: "เล่นต่อ",
        saveTitle: "บันทึกการประชุม",
        namePlaceholder: "ชื่อการประชุม",
        processBtn: "ประมวลผลและสร้างรายงาน",
        downloadMp3: "ดาวน์โหลด MP3"
    },
    landing: {
        welcomePrefix: "ยินดีต้อนรับกลับมา",
        recentMeetings: "การประชุมล่าสุด",
        recentSubtitle: "ประวัติการประมวลผลการประชุมอัจฉริยะของคุณ",
        viewAll: "ดูทั้งหมด",
        activeTasks: "งานที่กำลังดำเนินการ",
        activeSubtitle: "กำลังประมวลผลด้วย AI แบบเรียลไทม์",
        noActive: "ไม่มีงานที่กำลังดำเนินการในขณะนี้",
        processedCount: "การประชุมที่เสร็จสมบูรณ์",
        activeCount: "งานที่กำลังทำ",
        managerBtn: "เปิดตัวจัดการงาน",
        readAnalysis: "อ่านการวิเคราะห์",
        tableTitle: "หัวข้อการประชุม",
        tableDateTime: "วันและเวลา",
        tableStatus: "สถานะ",
        tableID: "ไอดี"
    },
    processing: {
        initializing: "กำลังเตรียมการ...",
        step: "ขั้นตอน",
        complete: "การประมวลผลเสร็จสมบูรณ์!",
        failed: "เกิดข้อผิดพลาด",
        cancelled: "ยกเลิกงานแล้ว",
        logsTitle: "บันทึกการทำงานแบบเรียลไทม์",
        downloadBtn: "ดาวน์โหลด DOCX",
        cancelBtn: "ยกเลิกการประมวลผล",
        closeBtn: "ปิด",
        statusComplete: "เสร็จสิ้น",
        statusFailed: "ล้มเหลว",
        statusCancelled: "ยกเลิกแล้ว"
    },
    queue: {
        title: "คิวการประมวลผล",
        subtitle: "สถานะการประมวลผลการประชุมด้วย AI แบบเรียลไทม์และประวัติการทำงาน",
        clearHistory: "ล้างประวัติ",
        pipelineStatus: "สถานะขั้นตอนการทำงาน",
        activeQueue: "คิวที่กำลังทำงาน",
        running: "กำลังทำงาน",
        noActive: "ไม่มีงานที่กำลังดำเนินการ เริ่มการประชุมใหม่เพื่อเริ่มต้น",
        logsTitle: "บันทึกการประมวลผล",
        statusFeed: "ฟีดสถานะ",
        taskHistory: "ประวัติงาน",
        noHistory: "ไม่พบประวัติการทำงาน",
        cancelConfirm: "คุณแน่ใจหรือไม่ว่าต้องการยกเลิกงานนี้?",
        deleteConfirm: "ลบงานนี้ออกจากประวัติ?",
        clearConfirm: "ล้างประวัติงานที่เสร็จสิ้นหรือล้มเหลวทั้งหมด?",
        downloadFailed: "ดาวน์โหลดไม่สำเร็จ ไฟล์อาจถูกลบไปแล้ว",
        cancelBtn: "ยกเลิกงาน"
    },
    setup: {
        title: "เตรียมการประชุมของคุณ",
        subtitle: "ระบุข้อมูลบริบทที่จำเป็นเพื่อให้ AI สามารถสรุปรายงานการประชุมและรายการสิ่งที่ต้องทำได้อย่างแม่นยำ",
        metadataTitle: "ข้อมูลพื้นฐานการประชุม",
        metadataDesc: "ข้อมูลระบุตัวตนที่สำคัญสำหรับการเก็บบันทึกรายงานการประชุม",
        fieldTitle: "หัวข้อการประชุม",
        fieldBU: "แผนก / หน่วยธุรกิจ",
        fieldTemplate: "เทมเพลตรายงานการประชุม",
        fieldDate: "วันที่",
        fieldTime: "เวลาเริ่ม",
        fieldAgenda: "วาระการประชุม",
        participantsTitle: "ผู้เข้าร่วมประชุม",
        participantsDesc: "ระบุรายชื่อผู้เข้าร่วมทั้งหมด เพื่อช่วยเพิ่มความแม่นยำในการระบุตัวผู้พูดระหว่างการถอดความ",
        participantPlaceholder: "เพิ่มอีเมลหรือชื่อ...",
        addBtn: "เพิ่ม",
        proceedBtn: "ดำเนินการอัดเสียง",
        errorEmpty: "กรุณากรอกข้อมูลที่จำเป็น (หัวข้อประชุม, วันที่, เวลาเริ่ม)",
        stepSetup: "ตั้งค่า",
        stepRecord: "อัดเสียง",
        stepProcess: "ประมวลผล",
        stepReview: "ตรวจสอบ",
        stepExport: "ส่งออก"
    }
};
